### ISSUE TITLE
[#1] Product Domain 구현

### ISSUE THREAD

**Issue by jaeyeonme** [f-lab-edu/event-blackfriday#1]
## 📌 Goal
상품 도메인의 핵심 기능 구현

## 📝 Details
1. Entity
   * Product 엔티티 및 JPA 매핑
   * BaseTimeEntity 구현
   * 재고 관리 메서드 (increase/decrease)

2. Validation
   * 필수값: 상품명, 설명
   * 가격: 0 이상
   * 재고: 음수 불가

3. Test
   * Entity 생성 테스트
   * 재고 관리 테스트
   * 유효성 검증 테스트

## ✅ Todo
- [x] BaseTimeEntity 구현
- [x] Product 엔티티 구현
- [x] 재고 관리 메서드 구현
- [x] 테스트 코드 작성
